import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';

/// Represents a date/time separator that appears between messages in the chat list.
///
/// Date headers are automatically inserted by the chat system to help users navigate
/// through conversation history by providing visual time markers. They appear when:
/// - Messages are separated by more than the configured time threshold (default 15 minutes)
/// - Messages span across different calendar days
/// - At the beginning of the chat to show when the first message was sent
///
/// The headers display human-readable date/time information and improve the user
/// experience by providing temporal context for message groups.
@immutable
class DateHeader extends Equatable {
  /// Creates a date header with the specified date/time and display text.
  ///
  /// The [dateTime] parameter represents the actual timestamp for this date marker,
  /// used for sorting and comparison operations in the message list.
  ///
  /// The [text] parameter contains the human-readable string that will be displayed
  /// to users, such as "Today", "Yesterday", "March 15, 2024", or "March 15, 10:30 AM".
  /// This text is typically generated by formatting functions that can be customized
  /// for different locales and date/time preferences.
  const DateHeader({required this.dateTime, required this.text});

  /// The actual date and time that this header represents.
  ///
  /// This timestamp is used by the chat system for:
  /// - Determining the correct position of the header in the chronological message list
  /// - Calculating time differences between messages for automatic header insertion
  /// - Sorting operations when messages are reordered or new messages arrive
  /// - Custom date formatting and localization
  ///
  /// The dateTime typically corresponds to the timestamp of the first message
  /// in a group that follows this header.
  final DateTime dateTime;

  /// The formatted text string that is displayed to users in the chat interface.
  ///
  /// This is the human-readable representation of the dateTime, formatted according
  /// to the chat's localization and date formatting settings. Examples include:
  /// - "Today" for messages sent today
  /// - "Yesterday" for messages from the previous day
  /// - "March 15, 2024" for specific dates
  /// - "March 15, 10:30 AM" for messages with both date and time
  /// - Localized versions like "Aujourd'hui", "Ayer", etc.
  ///
  /// The text generation can be customized through the chat's configuration
  /// to match application-specific formatting requirements and user preferences.
  final String text;

  /// Defines the properties used for equality comparison between DateHeader instances.
  ///
  /// Two DateHeader objects are considered equal if they have the same dateTime
  /// and text values. This enables efficient list operations and prevents duplicate
  /// headers from being inserted when the message list is updated.
  ///
  /// The equality comparison is used by:
  /// - Flutter's widget system to determine if UI rebuilds are necessary
  /// - List diff algorithms when calculating message list changes
  /// - Deduplication logic to prevent multiple headers for the same time period
  @override
  List<Object> get props => [dateTime, text];
}
